//
//  LoginInteractor.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func login(request: Login.Login.Request)
}

protocol LoginDataStore
{
    var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    var name: String = ""
    
    // MARK: Do something
    
    func login(request: Login.Login.Request)
    {
        worker = LoginWorker()
        worker?.doSomeWork()
        
        name = request.name
        
        if !name.isEmpty {
            // save name to UserDefaults
            UserDefaults().set(name, forKey: Constants.nameDefaultsKey)
        }
        
        let response = Login.Login.Response(success: !name.isEmpty)
        presenter?.presentResult(response: response)
    }
}
