//
//  LoginModels.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
        let name: String
    }
    struct Response
    {
        let success: Bool
    }
    struct ViewModel
    {
        let success: Bool
    }
  }
}
