//
//  MainPresenter.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentUser(response: Main.User.Response)
    func popToLogin()
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentUser(response: Main.User.Response) {
        let name = "Welcome back, \(response.name)"
        let viewModel = Main.User.ViewModel(name: name)
        
        viewController?.displayUser(viewModel: viewModel)
    }
    
    func popToLogin() {
        viewController?.popToLogin()
    }
}
