//
//  SplashRouter.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic
{
//  func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToLogin(segue: UIStoryboardSegue?)
    func routeToMain(segue: UIStoryboardSegue?)
}

protocol SplashDataPassing
{
  var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing
{
  weak var viewController: SplashViewController?
  var dataStore: SplashDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
    func routeToLogin(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard let destinationVC = segue.destination as? LoginViewController else { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as? LoginViewController else { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
            navigateToLogin(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToMain(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard let destinationVC = segue.destination as? MainViewController else { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMain(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainViewController") as? MainViewController else { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMain(source: dataStore!, destination: &destinationDS)
            navigateToMain(source: viewController!, destination: destinationVC)
        }
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SplashViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
    
    func navigateToLogin(source: SplashViewController, destination: LoginViewController) {
        DispatchQueue.main.async {
            let rootVC = UINavigationController(rootViewController: destination)
            rootVC.setNavigationBarHidden(true, animated: false)
            UIApplication.shared.keyWindow?.rootViewController = rootVC
        }
    }
    
    func navigateToMain(source: SplashViewController, destination: MainViewController) {
        DispatchQueue.main.async {
            let rootVC = UINavigationController(rootViewController: destination)
            rootVC.setNavigationBarHidden(true, animated: false)
            UIApplication.shared.keyWindow?.rootViewController = rootVC
        }
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SplashDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
    
    func passDataToLogin(source: SplashDataStore, destination: inout LoginDataStore) {
        
    }
    
    func passDataToMain(source: SplashDataStore, destination: inout MainDataStore) {
        destination.name = source.name
    }
}
