//
//  SplashPresenter.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic
{
    func presentName(response: Splash.LocalStorage.Response)
}

class SplashPresenter: SplashPresentationLogic
{
    weak var viewController: SplashDisplayLogic?
    
    // MARK: Do something
    
    //  func presentSomething(response: Splash.Something.Response)
    //  {
    //    let viewModel = Splash.Something.ViewModel()
    //    viewController?.displaySomething(viewModel: viewModel)
    //  }
    
    func presentName(response: Splash.LocalStorage.Response) {
        let viewModel = Splash.LocalStorage.ViewModel(success: response.success)
        viewController?.routeToPage(viewModel: viewModel)
    }
}
