//
//  SplashInteractor.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic
{
    func initialVC()
}

protocol SplashDataStore
{
    var name: String { get set }
}

class SplashInteractor: SplashBusinessLogic, SplashDataStore
{
    var presenter: SplashPresentationLogic?
    var worker: SplashWorker?
    var name: String = ""
    
    // MARK: Do something
    
    
    func initialVC() {
        name = UserDefaults().string(forKey: Constants.nameDefaultsKey) ?? ""
        
        switch name.isEmpty {
        case false:
            // goToMain
            let response = Splash.LocalStorage.Response(success: true)
            presenter?.presentName(response: response)
        case true:
            // goToLogin
            let response = Splash.LocalStorage.Response(success: false)
            presenter?.presentName(response: response)
        }
    }
}
