//
//  MainInteractor.swift
//  Learning-CleanSwift
//
//  Created by 7Peaks on 17/6/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func initialVC()
    func logout()
}

protocol MainDataStore
{
    var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    var name: String = ""
    
    // MARK: Do something
    
    func initialVC() {
        let resp = Main.User.Response(name: name)
        presenter?.presentUser(response: resp)
    }
    
    func logout() {
        //clear local data
        UserDefaults().removeObject(forKey: Constants.nameDefaultsKey)
        
        presenter?.popToLogin()
    }
}
